version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@1.1.0

jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: root
          MYSQL_DATABASE: webapp_test
    working_directory: ~/webapp
    steps:
      - checkout
      - restore_cache:
          name: bundle installの結果をリストア
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock"}}
            - v1-dependencies-
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      - run:
          name: context設定の環境変数
          command: |
            echo "${MYSQL_PASSWORD}"
            echo "${MYSQL_USER}"
            echo "${MYSQL_HOST}"
      - save_cache:
          name: bundle installの結果をキャッシュ
          paths: ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: データベースの起動を待機
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: データベースのセットアップ
          command: bundle exec rails db:schema:load
      - run:
          name: RSpecのテストを実行
          command: bundle exec rspec
  
  # イメージをビルドし、ECRへPUSH
  # build-stg-image-and-push:
  #   executor: container
  #   steps:
  #     - aws-ecr/build-and-push-image:
  #         aws-access-key-id: AWS_ACCESS_KEY_ID
  #         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  #         region: AWS_REGION
  #         repo: '${ECR_REPO_NAME}'
  #         extra-build-args: --target apps
  #         attach-workspace: true
  #         setup-remote-docker: true

  

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test

  # nginxイメージをビルドし、ECRへPUSH
  nginx-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          requires:
            - test
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: ./containers/nginx
          repo: webapp-nginx
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'neptune-task' # ECSのタスク定義名
          cluster-name: '${ECS_ARN}'  #ECSのクラスターのARN
          service-name: 'hello-service-3'  #サービス名
          container-image-name-updates: "container=webapp-nginx,tag=${CIRCLE_SHA1}"
  # railsイメージをビルドし、ECRへPUSH
  rails-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          requires:
            - test
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: .
          repo: webapp-rails
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'neptune-task' # ECSのタスク定義名
          cluster-name: '${ECS_ARN}' #ECSのクラスターのARN
          service-name: 'hello-service-3' #サービス名
          container-image-name-updates: "container=webapp-rails,tag=${CIRCLE_SHA1}"